name: ci

on:
  push:
    branches:
      - master

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'liberica'

      - name: Set up Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: Test libraries with Gradle
        run: ./gradlew clean check

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: "test-results/**/*.xml"
